### ISSUE TITLE
C style -> derefence breaks symbol matching

### ISSUE THREAD

**Issue by AdamBark** [mickeynp/smart-scan#16]
If the symbol under the cursor is foo->method foo- is the variable that gets searched for not foo.

**Comment by mickeynp** [comment]
Interesting. This is probably because - is not considered a symbol. I'll see if I can add "overrides" for certain languages. Thanks for the bug report Adam.

**Comment by AdamBark** [comment]
Thanks @mickeynp and @bmalehorn
